name: naf

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 mypy types-requests
        pip install -r requirements.txt
        python -m spacy download 'en-core-web-sm'
    - name: flake8
      run: |
        flake8 . --max-line-length=127
    - name: pytest
      run: |
        pytest tests/
    - name: typing
      run: |
        mypy --ignore-missing-imports .